import './globals.css'
import { Inter } from 'next/font/google'
import { SearchBar } from './components/searchbar/SearchBar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ReStore',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SearchBar />
        {children}
        </body>
    </html>
  )
}
